blog/urls.py
from django.contrib import admin
from django.urls import path,include
from myblog import views
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('myblog.urls')),
    path('myblog/', include('myblog.urls')),
    path('oauth/', include('social_django.urls', namespace="social")),
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myblog/urls.py
from django.urls import include,path
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('<int:id>/post_edit', views.post_edit, name='post_edit'),
    path('<int:id>/post_delete', views.post_delete, name='post_delete'),
    path('', views.post_list, name='post_list'),
    path('<int:id>/<slug>/', views.post_detail, name='post_detail'),
    path('post_create/', views.post_create, name='post_create'),

    path('login/', views.user_login, name='user_login'),
    path('logout/', views.user_logout, name='user_logout'),
    path('register/', views.register, name='register'),
    path('edit_profile/',views.edit_profile, name='edit_profile'),
    path('oauth/', include('social_django.urls', namespace="social")),
    path('like/', views.like_post, name='like_post'),
] 

if settings.DEBUG:
    urlpatterns == static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myblog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import pre_save
from django.dispatch import receiver
from django.utils.text import slugify
from django.urls import reverse

# Create your models here.

class PublishedManager(models.Manager):
	def get_queryset(self):
		return super(PublishedManager, self).get_queryset().filter(status='published')

class Post(models.Model):
	objects = models.Manager()
	published = PublishedManager()

	STATUS_CHOICES = {
	('draft','Draft'),
	('published','Published'),
	}

	title = models.CharField(max_length=100)
	slug = models.SlugField(max_length=120)
	author = models.ForeignKey(User, related_name='blog_posts', on_delete=models.CASCADE)
	body = models.TextField(default='')
	likes = models.ManyToManyField(User, related_name='like',blank=True)
	created = models.DateTimeField(auto_now_add=True) #auto_now_add is used at the time of creation
	updated = models.DateTimeField(auto_now=True) #auto_now is used while updating the created thing
	status = models.CharField(max_length=10, choices=STATUS_CHOICES, default='draft')
	restrict_comment = models.BooleanField(default=False)

	class Meta:
		ordering = ['-id']


	def __str__(self):
		return self.title

	def total_likes(self):
		return self.likes.count()

	def get_absolute_url(self):
		url = reverse("post_detail", kwargs={"id":self.id, "slug":self.slug})
		return url


@receiver(pre_save, sender=Post)
def pre_save_slug(sender, **kwargs):
	slug = slugify(kwargs['instance'].title)
	kwargs['instance'].slug = slug


class Profile(models.Model):
	user = models.OneToOneField(User, on_delete=models.CASCADE)
	dob = models.DateTimeField(null=True, blank=True)
	photo = models.ImageField(default='default.png', blank=True)

	def __str__(self):
		return "Profile Of User {}".format(self.user.username)


class Images(models.Model):
	post = models.ForeignKey(Post, on_delete=models.CASCADE)
	image = models.ImageField(upload_to='images/',blank=True, null=True)

	def __str__(self):
		return self.post.title + " Image"

class Comment(models.Model):
	post = models.ForeignKey(Post, on_delete=models.CASCADE)
	user = models.ForeignKey(User, on_delete=models.CASCADE)
	reply = models.ForeignKey('self', null=True, related_name='replies', on_delete=models.CASCADE)
	content = models.TextField(max_length=160)
	timestamp = models.DateTimeField(auto_now_add=True)


	def __str__(self):
		return '{}-{}'.format(self.post.title, str(self.user.username))

myblog/forms.py
from django import forms
from .models import Post, Profile, Comment
from django.contrib.auth.models import User

class PostCreateForm(forms.ModelForm):
	class Meta:
		model = Post
		fields = (
			'title',
			'body',
			'status',
			'restrict_comment',
			)

class PostEditForm(forms.ModelForm):
	class Meta:
		model = Post
		fields = (
			'title',
			'body',
			'status',
			'restrict_comment',
			)

class UserLoginForm(forms.Form):
	username = forms.CharField(label="")
	password = forms.CharField(label="", widget=forms.PasswordInput)

class UserRegistrationForm(forms.ModelForm):
	password = forms.CharField(widget=forms.PasswordInput(attrs={'placeholder':'Enter Password'}))
	confirm_password = forms.CharField(widget=forms.PasswordInput(attrs={'placeholder':'Confirm Password'}))
	class Meta:
		model = User
		fields = (
			'username',
			'first_name',
			'last_name',
			'email',
			)
	def clean_confirm_password(self):
		password = self.cleaned_data.get('password')
		confirm_password = self.cleaned_data.get('confirm_password')
		if password != confirm_password:
			raise forms.ValidationError("Password MisMatch")
		return confirm_password

class UserEditForm(forms.ModelForm):
	class Meta:
		model = User
		fields = (
			'username',
			'first_name',
			'last_name',
			'email',
			)
		
class ProfileEditForm(forms.ModelForm):
	class Meta:
		model = Profile
		exclude = ('user',)

class CommentForm(forms.ModelForm):
	content = forms.CharField(label="", widget=forms.Textarea(attrs={'class':'form-control', 'placeholder': 'Reply', 'rows':'4', 'cols': '50'}))
	class Meta:
		model = Comment
		fields = (
			'content',
			)

myblog/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse, Http404
from .models import Post, Profile, Images, Comment
from django.urls import reverse
from django.db.models import Q
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login, logout
from .forms import *
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.template.loader import render_to_string
from django.forms import modelformset_factory
from django.contrib import messages
# Create your views here.

def post_list(request):
	post_list = Post.published.all()
	query = request.GET.get('q')
	if query:
		post_list = Post.published.filter(
			Q(title__istartswith=query)|
			Q(title__iendswith=query)|
			Q(title__icontains=query)
			)
	paginator = Paginator(post_list, 5)
	page = request.GET.get('page')
	try:
		posts = paginator.page(page)
	except PageNotAnInteger:
		posts = paginator.page(1)

	except EmptyPage:
		posts = paginator.page(paginator.num_pages)

	if page is None:
		start_index = 0
		end_index = 7
	else:
		(start_index, end_index) = proper_pagination(posts, index=4)

	page_range = list(paginator.page_range)[start_index:end_index]
	context = {
		'posts':posts,
		'page_range':page_range,
	}
	return render(request, 'myblog/post_list.html',context)

def proper_pagination(posts, index):
	start_index = 0
	end_index = 7
	if posts.number > index:
		start_index = posts.number - index
		end_index = start_index + end_index
	return (start_index, end_index)


def post_detail(request, id, slug):
	posts = get_object_or_404(Post, id=id, slug=slug)
	comments = Comment.objects.filter(post=posts, reply=None).order_by('-id')
	is_liked = False
	if posts.likes.filter(id=request.user.id).exists():
		is_liked = True

	if request.method == "POST":
		comment_form = CommentForm(request.POST or None)
		if comment_form.is_valid():
			content = request.POST.get('content')
			reply_id = request.POST.get('comment_id')
			comment_qs = None
			if reply_id:
				comment_qs = Comment.objects.get(id=reply_id)
			comment = Comment.objects.create(post=posts, user=request.user, content=content, reply=comment_qs)
			comment.save()
			# return HttpResponseRedirect(posts.get_absolute_url())
	else:
		comment_form = CommentForm()
	context = {
		'posts':posts,
		'is_liked':is_liked,
		'total_likes':posts.total_likes(),
		'comments':comments,
		'comment_form': comment_form,
	}
	if request.is_ajax():
		html = render_to_string('myblog/comments.html', context, request)
		return JsonResponse({'form':html})
	return render(request, 'myblog/post_detail.html',context)

def like_post(request):
	# posts =get_object_or_404(Post, id=request.POST.get('post_id'))
	posts =get_object_or_404(Post, id=request.POST.get('id'))
	is_liked = False
	if posts.likes.filter(id=request.user.id).exists():
		posts.likes.remove(request.user)
		is_liked = False
	else:
		posts.likes.add(request.user)
		is_liked = True
	context = {
		'posts':posts,
		'is_liked':is_liked,
		'total_likes':posts.total_likes(),
	}
	if request.is_ajax():
		html = render_to_string('myblog/like_section.html', context, request)
		return JsonResponse({'form':html})


def get_absolute_url(self):
	return reverse("post_detail", kwargs={"slug":self.slug})


def post_create(request):
	ImageFormset = modelformset_factory(Images, fields=('image',), extra=4)
	if request.method == 'POST':
		form  = PostCreateForm(request.POST)
		formset = ImageFormset(request.POST or None, request.FILES or None)
		if form.is_valid() and formset.is_valid():
			post = form.save(commit=False)
			post.author = request.user
			post.save()
			print(formset.cleaned_data)

			for f in formset:
				try:
					# print(formset.cleaned_data)
					photo = Images(post=post, image=f.cleaned_data['image'])
					photo.save()
					

				except Exception as e:
					break
			messages.success(request, 'Post Created')
			return redirect('post_list')

			


	else:
		form = PostCreateForm()
		formset = ImageFormset(queryset=Images.objects.none())
	context = {
	'form':form,
	'formset':formset,
	}
	return render(request, 'myblog/post_create.html', context)




def post_edit(request, id):
	#instance are the data saved in database like title, body, status,etc
	
	post = get_object_or_404(Post, id=id)
	ImageFormset = modelformset_factory(Images, fields=('image',), extra=4, max_num=4)	
	if post.author != request.user:
		raise Http404()

	if request.method == 'POST':
		form  = PostEditForm(request.POST or None,instance=post)
		formset = ImageFormset(request.POST or None, request.FILES or None)
		if form.is_valid() and formset.is_valid():
			form.save()
			print(formset.cleaned_data)
			data = Images.objects.filter(post=post)

			for index, f in enumerate(formset):
				if f.cleaned_data:
					if f.cleaned_data['id'] is None:
						photo = Images(post=post, image=f.cleaned_data['image'])
						photo.save()
					elif f.cleaned_data['image'] is False:
						photo = Images.objects.get(id=request.POST.get('form-'+ str(index) +'-id'))
						photo.delete()
					else:
						photo = Images(post=post, image=f.cleaned_data.get('image'))
						d = Images.objects.get(id=data[index].id)
						d.image = photo.image
						d.save()
						# return HttpResponseRedirect(post.get_absolute_url())

			messages.info(request, '{} Post has been updated'.format(post.title))
			return HttpResponseRedirect(post.get_absolute_url())
	else:
		form = PostEditForm(instance=post)
		formset = ImageFormset(queryset=Images.objects.filter(post=post))
	context = {
	'form': form,
	'post':post,
	'formset':formset,
	
	}
	return render(request, 'myblog/post_edit.html', context)


def post_delete(request, id):
	post= get_object_or_404(Post, id=id)
	if request.user != post.author:
		raise Http404()
	post.delete()
	messages.warning(request, 'Post has been deleted')
	return redirect('post_list')





def user_login(request):
	if request.method == 'POST':
		form = UserLoginForm(request.POST)

		if form.is_valid():
			username = request.POST['username']
			password = request.POST['password']
			user = authenticate(username=username, password=password)
			if user:
				if user.is_active:
					login(request, user)
					return HttpResponseRedirect(reverse('post_list'))
				else:
					return HttpResponse('User is not active')
			else:
				return HttpResponse('Does not exist')
	else:
		form = UserLoginForm()

	context = {
		'form': form,
	}
	return render(request,'myblog/login.html',context)


def user_logout(request):
	logout(request)
	return redirect('post_list')

def register(request):
	if request.method == 'POST':
		form = UserRegistrationForm(request.POST or None)

		if form.is_valid():
			new_user = form.save(commit=False)
			new_user.set_password(form.cleaned_data['password'])
			new_user.save()
			Profile.objects.create(user=new_user)
			return redirect('post_list')
	else:
		form = UserRegistrationForm()

	context = {
		'form': form
	}
	return render(request,'myblog/register.html', context)

@login_required
def edit_profile(request):
	if request.method == 'POST':
		user_form = UserEditForm(data=request.POST or None, instance = request.user)
		profile_form = ProfileEditForm(data=request.POST or None, instance = request.user.profile, files=request.FILES)
		if user_form.is_valid() and profile_form.is_valid():
			user_form.save()
			profile_form.save()
			return HttpResponseRedirect(reverse('post_list'))
	else:
		user_form = UserEditForm(instance = request.user)
		profile_form = ProfileEditForm(instance = request.user.profile)

	context = {
	'user_form': user_form,
	'profile_form': profile_form,
	}

	return render(request, 'myblog/edit_profile.html', context)

myblog/templates/myblog/alerts.html
<div class="messages">
  {% if messages %}
    <ul class="messages">
    {% for m in messages %}
      <p class="alert alert-{{ m.tags }}">
        {{ m }}
      </p>

     {% endfor %}
  
    </ul>
  {% endif %}
</div>

myblog/templates/myblog/base.html
<!doctype html>
  {% load static %}
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'myblog/style.css' %}">
    <title>{% block title %} The Blog {% endblock %}</title>
  </head>
  <body style="margin-bottom: 150px;">
    {% include 'myblog/navbar.html' %}
  	<div class="container-fluid">
  		{% block content %}

      {% endblock %}
      {% include 'myblog/footer.html' %}
  	</div>
    

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script type="text/javascript">
    $(document).ready(function(event){  
      $('#delete').click(function(){
        return confirm("Are you sure you want to delete this?");
      });

      $(function(){
        setTimeout(function(){
          $('.alert').slideUp(500);
        }, 3000);
      });
      
      $('.reply-btn').click(function(){
        $(this).parent().parent().next('.replied-comments').fadeToggle();
      });


        $(document).on('click','#like', function(event){
          event.preventDefault();
          var pk = $(this).attr('value');
          $.ajax({
            type: 'POST',
            url: '{% url "like_post" %}',
            data: {'id':pk, 'csrfmiddlewaretoken':'{{ csrf_token }}'},
            dataType: 'json',
            success: function(response){
              $('#like-section').html(response['form'])
              console.log( $('#like-section').html(response['form']));
            },
            error: function(rs, e){
              console.log(rs.responseText);
            },
          });
        });

        $(document).on('submit','.comment-form',function(event){
          event.preventDefault();
          $.ajax({
            type:'POST',
            url: $(this).attr('action'),
            data: $(this).serialize(),
            dataType: 'json',
            success: function(response){
              $('.main-comment-section').html(response['form']);
              
              $('.reply-btn').click(function(){
                $(this).parent().parent().next('.replied-comments').fadeToggle();
                 
              });
            },
            error: function(rs, e){
              console.log(rs.responseText);
            },
          });
        });

        $(document).on('submit','.reply-form',function(event){
          event.preventDefault();
          $.ajax({
            type:'POST',
            url: $(this).attr('action'),
            data: $(this).serialize(),
            dataType: 'json',
            success: function(response){
              $('.main-comment-section').html(response['form']);
              
              $('.reply-btn').click(function(){
                $(this).parent().parent().next('.replied-comments').fadeToggle();
                 
              });
            },
            error: function(rs, e){
              console.log(rs.responseText);
            },
          });
        });

      });
    </script>
  </body>
</html>

myblog/templates/myblog/comments.html
<div class="main-comment-section">
          <div class="container-fluid mt-2">
            <div class="form-group row">
             {% if request.user.is_authenticated %}
        <form method="POST" class="comment-form" action=".">
          {% csrf_token %}
          {{ comment_form.as_p }}
          <input type="submit" class="btn btn-info" value="Submit">
          
        </form>
        {% endif %} 
            </div>  
          </div>
          {{ comments.count }} Comment{{ comments|pluralize }}<br><br>
          {% for comment in comments %}

            <blockquote class="blockquote">
              <p class="mb-0"><small>{{ comment.content }}</small></p>
              <footer class="blockquote-footer"><small>By-{{ comment.user| capfirst }}<cite title="Source Title"></cite></small>
                <button type="button" class="reply-btn btn btn-outline-dark btn-sm ml-2">Reply</button>
              </footer>
            </blockquote>
            <div class="replied-comments container mt-3" style="display:none;">
              {% for reply in comment.replies.all %}
                <blockquote class="blockquote">
                  <p class="mb-0"><small>{{ reply.content }}</small></p>
                  <footer class="blockquote-footer"><small>By-{{ reply.user| capfirst }}<cite title="Source Title"></cite></small></footer>
                </blockquote>
              {% endfor %}
              <div class="form-group row">
                {% if request.user.is_authenticated %}
                  <form method="POST" class="reply-form" action=".">
                     {% csrf_token %}
                     <input type="hidden" name="comment_id" value="{{ comment.id }}">
                    {{ comment_form.as_p }}
                    <input type="submit" class="btn btn-info" value="Submit">  
                  </form>
                {% endif %}
                
              </div>
              
            </div>
          {% endfor %}
          
        </div>

myblog/templates/myblog/edit_profile.html
{% extends 'myblog/base.html' %}
{% block title %}
Edit Profile | {{ block.super }}
{% endblock %}
{% block content %}
	<form method="POST" enctype="multipart/form-data">
		{% csrf_token %}
		<table class="table table-hover">
			{{ user_form }}
			{{ profile_form }}
		</table>
		<!-- {{ user_form.as_p }}
		{{ profile_form.as_p }} -->
		
		<input type="Submit" value="Update" class="btn btn-outline-dark">
		
	</form>
		<!-- <img src="{{ request.user.profile.photo.url }}" alt="Image"> -->
{% endblock %}

myblog/templates/myblog/footer.html
<footer class="bg-dark text-white" style="position: absolute;left: 0; right: 0; bottom: 0; height: 130px; padding: 15px;">
	<div class="row">
		<div class="col-md-4">
			<p><small> there welcome to the blog website powered by django framework on python. The developer will only be using djago for 3 more months. The developer has decided to take a look at node.js after that. Who knows anything can happen.</small></p>
		</div>
		<div class="col-md-4">
			<p><small> Hello there welcome to the blog website powered by django framework on python. The developer will only be using djago for 3 more months. The developer has decided to take a look at node.js after that. Who knows anything can happen.</small> </p>
		</div>
		<div class="col-md-4">
			<p><small> Hello there welcome to the blog website powered by django framework on python. The developer will only be using djago for 3 more months. The developer has decided to take a look at node.js after that. Who knows anything can happen.</small> </p>
		</div>
	</div>
	
</footer>

myblog/templates/myblog/like_section.html
{{ total_likes }} Like{{ total_likes|pluralize }}

        {% if request.user.is_authenticated %}
        <form action="{% url 'like_post' %}" method="POST">
        	{% csrf_token %}
        	{% if is_liked %}
        	<button type="submit" id="like" name="post_id" value="{{ posts.id }}" class="btn btn-danger">Dislike</button>
        	{% else %}
        	<button type="submit" id="like" name="post_id" value="{{ posts.id }}" class="btn btn-primary">Like</button>
        	{% endif %}
        </form>
        {% endif %}

myblog/templates/myblog/login.html
{% extends 'myblog/base.html' %}

{% block content %}

<form method="POST">
	{% csrf_token %}
	{{ form.as_p }}
	<small>
		<a href="{% url 'register' %}">Sign-up</a>
	</small><br>
	<input type="Submit" value="Login" class="btn btn-outline-success">
	<p>Or Login Via</p>
	<a href="{% url 'social:begin' 'github' %}">
		<button type="button" name="button" class="btn btn-outline-dark">Github</button>
	</a>
	<a href="{% url 'social:begin' 'google-oauth2' %}">
		<button type="button" name="button" class="btn btn-outline-danger">Google+</button>
	</a>
</form>

{% endblock %}

myblog/templates/myblog/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="{% url 'post_list' %}">The Blog</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      
      
      <form class="form-inline my-2 my-lg-0" action="{% url 'post_list' %}">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search" name="q">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
    </ul>
    <ul class="navbar-nav">
      {% if request.user.is_authenticated %}
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          {% if request.user.profile.photo %}
            <img src="{{ request.user.profile.photo.url }}" alt="Image" width="30" height="35" mr="1" class="rounded-circle chya">
          {% else %}
            <img src="/media/default.png" alt="Image" width="30" height="35" mr="1" class="rounded-circle chya">
          {% endif %}
          <span>Hi! {{ request.user|capfirst }}</span>
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="{% url 'edit_profile' %}">Edit Profile</a>
          <a class="dropdown-item" href="{% url 'post_create' %}">Post Create</a>
          <a class="dropdown-item" href="{% url 'user_logout' %}">Logout</a>
          
        </div>
      </li>
      {% else %}
      <li class="nav-item">
        <a href="{% url 'user_login' %}" class="nav-link">Login</a>
      </li>
      {% endif %}
    </ul>
  </div>
</nav>

myblog/templates/myblog/post_create.html
{% extends 'myblog/base.html' %}

{% block title %}
Add Blog
{% endblock %}

{% block content %}
<form method="post" enctype="multipart/form-data">
	{% csrf_token %}
	{{ form.as_p }}
	{{ formset.as_table }}
	<input type="submit" value="Create" class="btn btn-outline-success">
	
</form>
{% endblock %}

myblog/templates/myblog/post_detail.html
{% extends 'myblog/base.html' %}
      {% block title %} {{ posts.title }} | {{ block.super }} {% endblock %}
  		{% block content %}
      {% include 'myblog/alerts.html' %}
  			<h3>{{ posts.title}}</h3><br>
        
        <small>Created By: {{ posts.author}}</small><br>
        <hr>
        <p>{{ posts.body }}</p>

        <div class="row gallery"> 
          {% for p in posts.images_set.all %}
          <div class="col-md-3">
            <img src="{{ p.image.url }}" alt="Image not found" class="img-thumbnail">
          </div>

          {% endfor %}
        </div>
        
        <div id="like-section">
        	{% include 'myblog/like_section.html' %}
        </div>

        {% if posts.author == request.user %}
        <div class="section-1 my-5">
          <a href="{% url 'post_edit' id=posts.id %}" class="btn btn-info">Edit</a>
          <a href="{% url 'post_delete' id=posts.id %}" class="btn btn-danger" id="delete">Delete</a>
        </div>
        {% endif %}<br>
        <hr>
        {% if not posts.restrict_comment %}
          {% include 'myblog/comments.html' %}
        {% endif %}
  		{% endblock %}

myblog/templates/myblog/post_edit.html
{% extends 'myblog/base.html' %}
{% block title %} {{ post.title }} {% endblock %}
{% block content %}
	<form method="POST" enctype="multipart/form-data">
		{% csrf_token %}
		{{ form.as_p }}
		{{ formset.management_form }}
		{% for f in formset %}
			{{ f.as_p }}
		{% endfor %}
		<input type="submit" value="Update" class="btn btn-primary">
		
	</form>
{% endblock %}

myblog/templates/myblog/post_list.html
{% extends 'myblog/base.html' %}
{% block content %}
{% include 'myblog/alerts.html' %}

<div class="row">
  			{% for p in posts %}
  			<div class="col-md-6">
  				<div class="img-thumbnail">
  				<a href="{% url 'post_detail' p.id p.slug %}">{{p.title}}</a><small class="light" style="float:right">{{p.created}}</small><br>
  				Author:{{p.author}}
  				<br>
  				{{p.body}}<br>
  				</div><br>	
  			</div>
        {% empty %}
        <div class="container-fluid">
          <h3>
            No Posts Found having "{{ request.GET.q }}" in the title.
          </h3>
          
        </div>
			{% endfor %}
</div>

<ul class="pagination">
  {% if posts.has_previous %}
  <li class="page-item">
    <a href="?page={{ posts.previous_page_number }}" class="page-link">&laquo;</a>
  </li>
  {% endif %}
  {% for p in page_range %}
  {% if posts.number == p %}
  <li class="page-item active" >
    <a href="?page={{ p }}" class="page-link">{{ p }}</a>
  </li>
  {% else %}
  <li class="page-item" >
    <a href="?page={{ p }}" class="page-link">{{ p }}</a>
  </li>
  {% endif %}
  {% endfor %}
    {% if posts.has_next %}
  <li class="page-item">
    <a href="?page={{ posts.next_page_number }}" class="page-link">&raquo;</a>
  </li>
  {% endif %}
</ul>

{% endblock %}

myblog/templates/myblog/register.html
{% extends 'myblog/base.html' %}

{% block content %}
<form method="POST">
	{% csrf_token %}
	{{ form.as_p}}
	<input type="Submit" value="Register" class="btn btn-info">
	
</form>
{% endblock %}